/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const MatchDecision = IDL.Record({
  'id' : IDL.Principal,
  'decision' : IDL.Variant({ 'like' : IDL.Null, 'pass' : IDL.Null }),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'read' : IDL.Bool,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const PhotoPost = IDL.Record({
  'owner' : IDL.Principal,
  'timestamp' : Time,
  'caption' : IDL.Text,
  'photo' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInterest' : IDL.Func([IDL.Text], [IDL.Text], []),
  'addMatchDecision' : IDL.Func([MatchDecision], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPhotoPost' : IDL.Func([ExternalBlob, IDL.Text, Time], [], []),
  'createProfile' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [
        IDL.Record({
          'id' : IDL.Principal,
          'age' : IDL.Nat,
          'bio' : IDL.Text,
          'displayName' : IDL.Text,
          'interests' : IDL.Vec(IDL.Text),
        }),
      ],
      [],
    ),
  'findUsersMatchingInterestQuery' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Principal,
            'age' : IDL.Nat,
            'bio' : IDL.Text,
            'displayName' : IDL.Text,
            'interests' : IDL.Vec(IDL.Text),
          })
        ),
      ],
      [],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], []),
  'getCallerUserProfile' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Record({
            'id' : IDL.Principal,
            'age' : IDL.Nat,
            'bio' : IDL.Text,
            'displayName' : IDL.Text,
            'interests' : IDL.Vec(IDL.Text),
          })
        ),
      ],
      [],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'sent' : IDL.Vec(Message),
          'unreadCount' : IDL.Nat,
          'received' : IDL.Vec(Message),
        }),
      ],
      [],
    ),
  'getFeed' : IDL.Func(
      [IDL.Vec(IDL.Principal), IDL.Nat],
      [IDL.Vec(PhotoPost)],
      ['query'],
    ),
  'getOwnProfileQuery' : IDL.Func(
      [],
      [
        IDL.Record({
          'id' : IDL.Principal,
          'age' : IDL.Nat,
          'bio' : IDL.Text,
          'displayName' : IDL.Text,
          'interests' : IDL.Vec(IDL.Text),
        }),
      ],
      [],
    ),
  'getPhotoPost' : IDL.Func([IDL.Nat], [IDL.Opt(PhotoPost)], ['query']),
  'getProfileByIdQuery' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'id' : IDL.Principal,
          'age' : IDL.Nat,
          'bio' : IDL.Text,
          'displayName' : IDL.Text,
          'interests' : IDL.Vec(IDL.Text),
        }),
      ],
      [],
    ),
  'getProfileWithPosts' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Opt(
          IDL.Record({
            'id' : IDL.Principal,
            'age' : IDL.Nat,
            'bio' : IDL.Text,
            'displayName' : IDL.Text,
            'photoPosts' : IDL.Vec(PhotoPost),
            'interests' : IDL.Vec(IDL.Text),
          })
        ),
      ],
      ['query'],
    ),
  'getProfiles' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Principal,
            'age' : IDL.Nat,
            'bio' : IDL.Text,
            'displayName' : IDL.Text,
            'interests' : IDL.Vec(IDL.Text),
          })
        ),
      ],
      [],
    ),
  'getUserMatchesQuery' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MatchDecision)],
      [],
    ),
  'getUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(PhotoPost)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Opt(
          IDL.Record({
            'id' : IDL.Principal,
            'age' : IDL.Nat,
            'bio' : IDL.Text,
            'displayName' : IDL.Text,
            'interests' : IDL.Vec(IDL.Text),
          })
        ),
      ],
      [],
    ),
  'getUserProfileWithPosts' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Opt(
          IDL.Record({
            'id' : IDL.Principal,
            'age' : IDL.Nat,
            'bio' : IDL.Text,
            'displayName' : IDL.Text,
            'photoPosts' : IDL.Vec(PhotoPost),
            'interests' : IDL.Vec(IDL.Text),
          })
        ),
      ],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAsRead' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func(
      [
        IDL.Record({
          'id' : IDL.Principal,
          'age' : IDL.Nat,
          'bio' : IDL.Text,
          'displayName' : IDL.Text,
          'interests' : IDL.Vec(IDL.Text),
        }),
      ],
      [],
      [],
    ),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text, Time], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const MatchDecision = IDL.Record({
    'id' : IDL.Principal,
    'decision' : IDL.Variant({ 'like' : IDL.Null, 'pass' : IDL.Null }),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'read' : IDL.Bool,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const PhotoPost = IDL.Record({
    'owner' : IDL.Principal,
    'timestamp' : Time,
    'caption' : IDL.Text,
    'photo' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInterest' : IDL.Func([IDL.Text], [IDL.Text], []),
    'addMatchDecision' : IDL.Func([MatchDecision], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPhotoPost' : IDL.Func([ExternalBlob, IDL.Text, Time], [], []),
    'createProfile' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [
          IDL.Record({
            'id' : IDL.Principal,
            'age' : IDL.Nat,
            'bio' : IDL.Text,
            'displayName' : IDL.Text,
            'interests' : IDL.Vec(IDL.Text),
          }),
        ],
        [],
      ),
    'findUsersMatchingInterestQuery' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Principal,
              'age' : IDL.Nat,
              'bio' : IDL.Text,
              'displayName' : IDL.Text,
              'interests' : IDL.Vec(IDL.Text),
            })
          ),
        ],
        [],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], []),
    'getCallerUserProfile' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Record({
              'id' : IDL.Principal,
              'age' : IDL.Nat,
              'bio' : IDL.Text,
              'displayName' : IDL.Text,
              'interests' : IDL.Vec(IDL.Text),
            })
          ),
        ],
        [],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'sent' : IDL.Vec(Message),
            'unreadCount' : IDL.Nat,
            'received' : IDL.Vec(Message),
          }),
        ],
        [],
      ),
    'getFeed' : IDL.Func(
        [IDL.Vec(IDL.Principal), IDL.Nat],
        [IDL.Vec(PhotoPost)],
        ['query'],
      ),
    'getOwnProfileQuery' : IDL.Func(
        [],
        [
          IDL.Record({
            'id' : IDL.Principal,
            'age' : IDL.Nat,
            'bio' : IDL.Text,
            'displayName' : IDL.Text,
            'interests' : IDL.Vec(IDL.Text),
          }),
        ],
        [],
      ),
    'getPhotoPost' : IDL.Func([IDL.Nat], [IDL.Opt(PhotoPost)], ['query']),
    'getProfileByIdQuery' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'id' : IDL.Principal,
            'age' : IDL.Nat,
            'bio' : IDL.Text,
            'displayName' : IDL.Text,
            'interests' : IDL.Vec(IDL.Text),
          }),
        ],
        [],
      ),
    'getProfileWithPosts' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Opt(
            IDL.Record({
              'id' : IDL.Principal,
              'age' : IDL.Nat,
              'bio' : IDL.Text,
              'displayName' : IDL.Text,
              'photoPosts' : IDL.Vec(PhotoPost),
              'interests' : IDL.Vec(IDL.Text),
            })
          ),
        ],
        ['query'],
      ),
    'getProfiles' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Principal,
              'age' : IDL.Nat,
              'bio' : IDL.Text,
              'displayName' : IDL.Text,
              'interests' : IDL.Vec(IDL.Text),
            })
          ),
        ],
        [],
      ),
    'getUserMatchesQuery' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MatchDecision)],
        [],
      ),
    'getUserPosts' : IDL.Func([IDL.Principal], [IDL.Vec(PhotoPost)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Opt(
            IDL.Record({
              'id' : IDL.Principal,
              'age' : IDL.Nat,
              'bio' : IDL.Text,
              'displayName' : IDL.Text,
              'interests' : IDL.Vec(IDL.Text),
            })
          ),
        ],
        [],
      ),
    'getUserProfileWithPosts' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Opt(
            IDL.Record({
              'id' : IDL.Principal,
              'age' : IDL.Nat,
              'bio' : IDL.Text,
              'displayName' : IDL.Text,
              'photoPosts' : IDL.Vec(PhotoPost),
              'interests' : IDL.Vec(IDL.Text),
            })
          ),
        ],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAsRead' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func(
        [
          IDL.Record({
            'id' : IDL.Principal,
            'age' : IDL.Nat,
            'bio' : IDL.Text,
            'displayName' : IDL.Text,
            'interests' : IDL.Vec(IDL.Text),
          }),
        ],
        [],
        [],
      ),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text, Time], [], []),
  });
};

export const init = ({ IDL }) => { return []; };