/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface MatchDecision {
  'id' : Principal,
  'decision' : { 'like' : null } |
    { 'pass' : null },
}
export interface Message {
  'content' : string,
  'read' : boolean,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
}
export interface PhotoPost {
  'owner' : Principal,
  'timestamp' : Time,
  'caption' : string,
  'photo' : ExternalBlob,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInterest' : ActorMethod<[string], string>,
  'addMatchDecision' : ActorMethod<[MatchDecision], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPhotoPost' : ActorMethod<[ExternalBlob, string, Time], undefined>,
  'createProfile' : ActorMethod<
    [string, bigint, string],
    {
      'id' : Principal,
      'age' : bigint,
      'bio' : string,
      'displayName' : string,
      'interests' : Array<string>,
    }
  >,
  'findUsersMatchingInterestQuery' : ActorMethod<
    [string],
    Array<
      {
        'id' : Principal,
        'age' : bigint,
        'bio' : string,
        'displayName' : string,
        'interests' : Array<string>,
      }
    >
  >,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<
    [],
    [] | [
      {
        'id' : Principal,
        'age' : bigint,
        'bio' : string,
        'displayName' : string,
        'interests' : Array<string>,
      }
    ]
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<
    [Principal],
    {
      'sent' : Array<Message>,
      'unreadCount' : bigint,
      'received' : Array<Message>,
    }
  >,
  'getFeed' : ActorMethod<[Array<Principal>, bigint], Array<PhotoPost>>,
  'getOwnProfileQuery' : ActorMethod<
    [],
    {
      'id' : Principal,
      'age' : bigint,
      'bio' : string,
      'displayName' : string,
      'interests' : Array<string>,
    }
  >,
  'getPhotoPost' : ActorMethod<[bigint], [] | [PhotoPost]>,
  'getProfileByIdQuery' : ActorMethod<
    [Principal],
    {
      'id' : Principal,
      'age' : bigint,
      'bio' : string,
      'displayName' : string,
      'interests' : Array<string>,
    }
  >,
  'getProfileWithPosts' : ActorMethod<
    [Principal],
    [] | [
      {
        'id' : Principal,
        'age' : bigint,
        'bio' : string,
        'displayName' : string,
        'photoPosts' : Array<PhotoPost>,
        'interests' : Array<string>,
      }
    ]
  >,
  'getProfiles' : ActorMethod<
    [],
    Array<
      {
        'id' : Principal,
        'age' : bigint,
        'bio' : string,
        'displayName' : string,
        'interests' : Array<string>,
      }
    >
  >,
  'getUserMatchesQuery' : ActorMethod<[Principal], Array<MatchDecision>>,
  'getUserPosts' : ActorMethod<[Principal], Array<PhotoPost>>,
  'getUserProfile' : ActorMethod<
    [Principal],
    [] | [
      {
        'id' : Principal,
        'age' : bigint,
        'bio' : string,
        'displayName' : string,
        'interests' : Array<string>,
      }
    ]
  >,
  'getUserProfileWithPosts' : ActorMethod<
    [Principal],
    [] | [
      {
        'id' : Principal,
        'age' : bigint,
        'bio' : string,
        'displayName' : string,
        'photoPosts' : Array<PhotoPost>,
        'interests' : Array<string>,
      }
    ]
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAsRead' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<
    [
      {
        'id' : Principal,
        'age' : bigint,
        'bio' : string,
        'displayName' : string,
        'interests' : Array<string>,
      },
    ],
    undefined
  >,
  'sendMessage' : ActorMethod<[Principal, string, Time], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];