/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Message {
    content: string;
    read: boolean;
    recipient: Principal;
    sender: Principal;
    timestamp: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PhotoPost {
    owner: Principal;
    timestamp: Time;
    caption: string;
    photo: ExternalBlob;
}
export interface MatchDecision {
    id: Principal;
    decision: Variant_like_pass;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_like_pass {
    like = "like",
    pass = "pass"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addInterest(interest: string): Promise<string>;
    addMatchDecision(likeDecision: MatchDecision): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPhotoPost(photo: ExternalBlob, caption: string, timestamp: Time): Promise<void>;
    createProfile(displayName: string, age: bigint, bio: string): Promise<{
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        interests: Array<string>;
    }>;
    findUsersMatchingInterestQuery(interest: string): Promise<Array<{
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        interests: Array<string>;
    }>>;
    getAllUsers(): Promise<Array<Principal>>;
    getCallerUserProfile(): Promise<{
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        interests: Array<string>;
    } | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversation(partner: Principal): Promise<{
        sent: Array<Message>;
        unreadCount: bigint;
        received: Array<Message>;
    }>;
    getFeed(matchedUsers: Array<Principal>, _limit: bigint): Promise<Array<PhotoPost>>;
    getOwnProfileQuery(): Promise<{
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        interests: Array<string>;
    }>;
    getPhotoPost(_postId: bigint): Promise<PhotoPost | null>;
    getProfileByIdQuery(id: Principal): Promise<{
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        interests: Array<string>;
    }>;
    getProfileWithPosts(id: Principal): Promise<{
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        photoPosts: Array<PhotoPost>;
        interests: Array<string>;
    } | null>;
    getProfiles(): Promise<Array<{
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        interests: Array<string>;
    }>>;
    getUserMatchesQuery(user: Principal): Promise<Array<MatchDecision>>;
    getUserPosts(user: Principal): Promise<Array<PhotoPost>>;
    getUserProfile(user: Principal): Promise<{
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        interests: Array<string>;
    } | null>;
    getUserProfileWithPosts(user: Principal): Promise<{
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        photoPosts: Array<PhotoPost>;
        interests: Array<string>;
    } | null>;
    isCallerAdmin(): Promise<boolean>;
    markAsRead(partner: Principal): Promise<void>;
    saveCallerUserProfile(profile: {
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        interests: Array<string>;
    }): Promise<void>;
    sendMessage(recipient: Principal, content: string, timestamp: Time): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, MatchDecision as _MatchDecision, PhotoPost as _PhotoPost, Time as _Time, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addInterest(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addInterest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInterest(arg0);
            return result;
        }
    }
    async addMatchDecision(arg0: MatchDecision): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMatchDecision(to_candid_MatchDecision_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMatchDecision(to_candid_MatchDecision_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPhotoPost(arg0: ExternalBlob, arg1: string, arg2: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPhotoPost(await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPhotoPost(await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async createProfile(arg0: string, arg1: bigint, arg2: string): Promise<{
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        interests: Array<string>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async findUsersMatchingInterestQuery(arg0: string): Promise<Array<{
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        interests: Array<string>;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.findUsersMatchingInterestQuery(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findUsersMatchingInterestQuery(arg0);
            return result;
        }
    }
    async getAllUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<{
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        interests: Array<string>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: Principal): Promise<{
        sent: Array<Message>;
        unreadCount: bigint;
        received: Array<Message>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return result;
        }
    }
    async getFeed(arg0: Array<Principal>, arg1: bigint): Promise<Array<PhotoPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeed(arg0, arg1);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeed(arg0, arg1);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnProfileQuery(): Promise<{
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        interests: Array<string>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnProfileQuery();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnProfileQuery();
            return result;
        }
    }
    async getPhotoPost(arg0: bigint): Promise<PhotoPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotoPost(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotoPost(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfileByIdQuery(arg0: Principal): Promise<{
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        interests: Array<string>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileByIdQuery(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileByIdQuery(arg0);
            return result;
        }
    }
    async getProfileWithPosts(arg0: Principal): Promise<{
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        photoPosts: Array<PhotoPost>;
        interests: Array<string>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileWithPosts(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileWithPosts(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfiles(): Promise<Array<{
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        interests: Array<string>;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfiles();
            return result;
        }
    }
    async getUserMatchesQuery(arg0: Principal): Promise<Array<MatchDecision>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserMatchesQuery(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserMatchesQuery(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPosts(arg0: Principal): Promise<Array<PhotoPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPosts(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPosts(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<{
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        interests: Array<string>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfileWithPosts(arg0: Principal): Promise<{
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        photoPosts: Array<PhotoPost>;
        interests: Array<string>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfileWithPosts(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfileWithPosts(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAsRead(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAsRead(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: {
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        interests: Array<string>;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string, arg2: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_MatchDecision_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchDecision): MatchDecision {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_PhotoPost_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PhotoPost): Promise<PhotoPost> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        interests: Array<string>;
    }]): {
    id: Principal;
    age: bigint;
    bio: string;
    displayName: string;
    interests: Array<string>;
} | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PhotoPost]): Promise<PhotoPost | null> {
    return value.length === 0 ? null : await from_candid_PhotoPost_n18(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        id: Principal;
        age: bigint;
        bio: string;
        displayName: string;
        photoPosts: Array<_PhotoPost>;
        interests: Array<string>;
    }]): Promise<{
    id: Principal;
    age: bigint;
    bio: string;
    displayName: string;
    photoPosts: Array<PhotoPost>;
    interests: Array<string>;
} | null> {
    return value.length === 0 ? null : await from_candid_record_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: Principal;
    timestamp: _Time;
    caption: string;
    photo: _ExternalBlob;
}): Promise<{
    owner: Principal;
    timestamp: Time;
    caption: string;
    photo: ExternalBlob;
}> {
    return {
        owner: value.owner,
        timestamp: value.timestamp,
        caption: value.caption,
        photo: await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.photo)
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    age: bigint;
    bio: string;
    displayName: string;
    photoPosts: Array<_PhotoPost>;
    interests: Array<string>;
}): Promise<{
    id: Principal;
    age: bigint;
    bio: string;
    displayName: string;
    photoPosts: Array<PhotoPost>;
    interests: Array<string>;
}> {
    return {
        id: value.id,
        age: value.age,
        bio: value.bio,
        displayName: value.displayName,
        photoPosts: await from_candid_vec_n17(_uploadFile, _downloadFile, value.photoPosts),
        interests: value.interests
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    decision: {
        like: null;
    } | {
        pass: null;
    };
}): {
    id: Principal;
    decision: Variant_like_pass;
} {
    return {
        id: value.id,
        decision: from_candid_variant_n27(_uploadFile, _downloadFile, value.decision)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    like: null;
} | {
    pass: null;
}): Variant_like_pass {
    return "like" in value ? Variant_like_pass.like : "pass" in value ? Variant_like_pass.pass : value;
}
async function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PhotoPost>): Promise<Array<PhotoPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PhotoPost_n18(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MatchDecision>): Array<MatchDecision> {
    return value.map((x)=>from_candid_MatchDecision_n25(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MatchDecision_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchDecision): _MatchDecision {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    decision: Variant_like_pass;
}): {
    id: Principal;
    decision: {
        like: null;
    } | {
        pass: null;
    };
} {
    return {
        id: value.id,
        decision: to_candid_variant_n10(_uploadFile, _downloadFile, value.decision)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_like_pass): {
    like: null;
} | {
    pass: null;
} {
    return value == Variant_like_pass.like ? {
        like: null
    } : value == Variant_like_pass.pass ? {
        pass: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
